project:
  type: website
  output-dir: docs

website:
  comments:
    giscus:
      repo: JCfly3000/into_AI
      input-position: "bottom"
      theme:
        light: light # giscus theme used for light website theme
        dark: dark_dimmed # giscus theme used for dark website theme

  title: "AI handbook"
  favicon: "Piktogramm-AI-100.jpg"
  navbar:
    logo: "Piktogramm-AI-100.jpg"
    left:
      - href: index.qmd
        text: Home
      - href: LLM.qmd
        text: LLM
      - href: ellmer.qmd
        text: ellmer
      - href: chatlas.qmd
        text: chatlas
      - href: chattr.qmd
        text: chattr  
      - href: gemini.qmd
        text: gemini
      - href: mlx_lm python.qmd
        text: mlx_lm    
      
    right:
      - icon: github
        href: https://github.com/JCfly3000/into_AI

  page-footer:
    right: "This blog is built with ❤️ and [Quarto](https://quarto.org/)."
    
format:
  html:
 
    theme:   
      light: cosmo
      dark: darkly
    css: styles.css
    grid:
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem


resources:
  - "output_data/*"

filters:
  - foldableCodeBlcok.lua

babelquarto:
  languagecodes:
  - name: cn
    text: "中文"
  - name: en
    text: "EN"
  mainlanguage: 'en'
  languages: ['cn']
title-cn: AI手册
description-cn: description in cn
author-cn: author in cn
lang: en
