[project]
name = "into-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mlx-lm>=0.25.2",
    "nbclient>=0.10.2",
    "nbformat>=5.10.4",
]
